GameEncyclopediaCore/Controllers/VideoGamesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GameEncyclopediaCore.Models.VideoGameViewModels;
using GameEncyclopediaCore.Services;
using GameEncyclopediaCore.Utils;
using Microsoft.AspNetCore.Mvc;

namespace GameEncyclopediaCore.Controllers
{
    public class VideoGamesController : Controller
    {
        private readonly IVideoGameService _videoGameService;

        public VideoGamesController(IVideoGameService videoGameService)
        {
            _videoGameService = videoGameService;
        }

        public async Task<IActionResult> Index()
        {
            ViewBag.CountAfterRelease = await _videoGameService.CountVideoGames(g => g.ReleaseDate <= DateTime.Now);

            ViewBag.CountBeforeRelease = await _videoGameService.CountVideoGames(g => g.ReleaseDate <= DateTime.Now);

            return View();
        }
    }
}

GameEncyclopediaCore/Views/Shared/_AlertPartial.cshtml
<div class="alert @(ViewBag.Errors == null ? "alert-success" : "alert-danger") alert-dismissible fade show" role="alert">
    @if (ViewBag.Errors == null)
    {
        @AccountResource.AccountUpdatedSuccessfully
    }
    else
    {
        @AccountResource.ErrorOccuredWhileUpdatingAccount
        <ul>
            @foreach (var error in (IEnumerable<string>)ViewBag.Errors)
            {
                <li>@error</li>
            }
        </ul>
    }
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

GameEncyclopediaCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - @CommonResource.GameEncyclopedia</title>

    <link rel="icon" type="image/x-icon" href="~/images/favicon.jpg" />
    <link rel="shortcut icon" type="image/x-icon" href="~/images/favicon.jpg" />

    <environment include="Development">
        <link rel="stylesheet" href="~/node_modules/bootstrap/dist/css/bootstrap.css" />
        <link href="~/node_modules/font-awesome/css/font-awesome.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/4.1.1/css/bootstrap.min.css"
              asp-fallback-href="~/node_modules/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
              asp-fallback-href="~/node_modules/font-awesome/css/font-awesome.min.css"
              asp-fallback-test-class="fa" asp-fallback-test-property="display" asp-fallback-test-value="inline-block" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <link href="~/node_modules/jquery-ui/themes/base/base.css" rel="stylesheet" />
    <link href="~/node_modules/jquery-ui/themes/base/theme.css" rel="stylesheet" />
    <link href="~/node_modules/jquery-ui/themes/base/slider.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" asp-action="Index" asp-controller="Home">
            <img src="~/images/favicon.jpg" width="30" height="30" class="d-inline-block align-top" alt="GE">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" asp-action="Index" asp-controller="Home"><i class="fa fa-home"></i> <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-action="Index" asp-controller="News">@CommonResource.News</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-action="Index" asp-controller="VideoGames">@CommonResource.Games</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-action="Index" asp-controller="Articles">@CommonResource.Articles</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-action="Index" asp-controller="Solutions">@CommonResource.Solutions</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-action="Index" asp-controller="Reviews">@CommonResource.Reviews</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <form asp-action="Search" asp-controller="Games" method="get" class="form-inline my-2 my-lg-0">
                        <input class="form-control mr-sm-2" type="search" placeholder="@CommonResource.SearchGames" aria-label="Search">
                        <button class="btn btn-outline-danger my-2 my-sm-0" type="submit"><i class="fa fa-search"></i></button>
                    </form>
                </li>
                <partial name="_LoginPartial" model='TempData["loginViewModel"]' />
            </ul>

        </div>
    </nav>
    <div id="alertBox"></div>
    <partial name="_CookieConsentPartial" />
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p style="float: left;">&copy; @DateTime.Now.Year - @CommonResource.GameEncyclopedia</p>
            <ul style="float: right;" class="nav">
                <li class="nav-item">
                    <a class="nav-link" asp-action="About" asp-controller="Home">@CommonResource.About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-action="Contact" asp-controller="Home">@CommonResource.Contact</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-action="Rules" asp-controller="Home">@CommonResource.Rules</a>
                </li>
            </ul>
        </footer>
    </div>
    <environment include="Development">
        <script src="~/node_modules/jquery/dist/jquery.js"></script>
        <script src="~/node_modules/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/node_modules/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/node_modules/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/node_modules/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/4.1.1/bootstrap.js"
                asp-fallback-src="~/node_modules/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.17.0/jquery.validate.min.js"
                asp-fallback-src="~/node_modules/jquery-validation/dist/jquery.validate.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.validator"></script>
        <script src="https://ajax.aspnetcdn.com/ajax/mvc/5.2.3/jquery.validate.unobtrusive.min.js"
                asp-fallback-src="~/node_modules/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js"
                asp-fallback-test="window.jQuery && window.jQuery.validator && window.jQuery.validator.unobtrusive">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    @RenderSection("scripts", required: false)
</body>
</html>